server:
  port: 8080 # Gateway server port

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/authentication/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/all/**


management:
  endpoints:
    web:
      exposure:
        include: "*"
