server:
  port: 8080 # Gateway server port

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Authorization, $httpRequest.headers.Authorization
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/authentication/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/all/**
        - id: appointment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/appointments/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, "Bearer #{request.headers.Authorization}"
        - id: doctor-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/doctors/**, /api/v1/schedules/**
          filters:
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=Authorization, "Bearer #{request.headers.Authorization}"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
