server:
  port: 8085  # Gateway server port

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          # uri: lb://auth-service
          predicates:
            - Path=/api/v1/authentication/**
        - id: user-service
          uri: http://localhost:8081
          # uri: lb://book-service
          predicates:
            - Path=/api/v1/users/**

management:
  endpoints:
    web:
      exposure:
        include: "*"